### ISSUE TITLE
Replace fingerprint for WS sim. searches

### ISSUE THREAD

**Issue by madgpap** [chembl/mychembl#18]
Change from torsionbv_fp to morganbv_fp or rdkit_fp.
Snippet:

    select molregno, m as smiles, tanimoto_sml(morganbv_fp('CCCc1nn(C)c2C(=O)NC(=Nc12)c3cc(ccc3OCC)S(=O)(=O)N4CCN(C)CC4'::mol),mfp2) as similarity
    from fps_rdkit join mols_rdkit using (molregno)
    where morganbv_fp('CCCc1nn(C)c2C(=O)NC(=Nc12)c3cc(ccc3OCC)S(=O)(=O)N4CCN(C)CC4'::mol)%mfp2
    order by morganbv_fp('CCCc1nn(C)c2C(=O)NC(=Nc12)c3cc(ccc3OCC)S(=O)(=O)N4CCN(C)CC4'::mol)<%>mfp2;

**Comment by mnowotka** [comment]
Done.
