### ISSUE TITLE
Create a default virtualenv

### ISSUE THREAD

**Issue by mnowotka** [chembl/mychembl#2]
So far we have bunch of

    sudo pip install ....

Commands, accumulated in https://github.com/chembl/mychembl/blob/master/install_py_libs.sh. The problem is, these are installed globally, requiring sudo privileges and interfere with other packages installed by `sudo apt-get install ...`. 

The ideas would be to create default virtualenv and add a line in `chembl's` `bashrc` to activate it automatically.

**Comment by madgpap** [comment]
we are using conda now
