### ISSUE TITLE
Use conda

### ISSUE THREAD

**Issue by mnowotka** [chembl/mychembl#27]
We should at least try to use conda for one release in order to evaluate it.
This can potentially make installing rdkit lot easier.

But there is one more thing - there will be point in the future when we decide to use Python 3 by default. On the other hand it could be difficult to convert all our software to Python 3 in one go. So at least one future myChEMBL release will have to have two different python versions installed. This is the case where conda can be very helpful.

**Comment by madgpap** [comment]
although conda is free to use, we should check their license for the right to distribute.

**Comment by mnowotka** [comment]
It's free to distribute: https://github.com/conda/conda/blob/master/LICENSE.txt

**Comment by madgpap** [comment]
miniconda

**Comment by madgpap** [comment]
```
curl -o miniconda.sh http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
bash miniconda.sh
conda create -n rd27 python=2.7
source activate rd27
conda install ipython ipython-notebook pillow pandas
conda install -c https://conda.anaconda.org/rdkit rdkit
```
